fix: cluster

diff --git a/.github/actions/build-image-action/action.yml b/.github/actions/build-image-action/action.yml
--- a/.github/actions/build-image-action/action.yml
+++ b/.github/actions/build-image-action/action.yml
@@ -88,32 +88,32 @@ runs:
 
     - name: Check and Create Kind Cluster
       run: |
-        export KUBECONFIG=~/.kube/config
-        echo "Using kubeconfig at $KUBECONFIG."
+        # export KUBECONFIG=~/.kube/config
+        # echo "Using kubeconfig at $KUBECONFIG."
 
-        function clean_kindnet_resources() {
-          if ! kubectl cluster-info &> /dev/null; then
-            echo "Cannot reach cluster. Skipping cleanup."
-            return
-          fi
+        # function clean_kindnet_resources() {
+        #   if ! kubectl cluster-info &> /dev/null; then
+        #     echo "Cannot reach cluster. Skipping cleanup."
+        #     return
+        #   fi
 
-          echo "Cleaning up kindnet resources..."
-          kubectl delete clusterrole kindnet --ignore-not-found
-          kubectl delete clusterrolebinding kindnet --ignore-not-found
-          kubectl delete serviceaccount kindnet -n kube-system --ignore-not-found
-          kubectl delete daemonset kindnet -n kube-system --ignore-not-found
-        }
+        #   echo "Cleaning up kindnet resources..."
+        #   kubectl delete clusterrole kindnet --ignore-not-found
+        #   kubectl delete clusterrolebinding kindnet --ignore-not-found
+        #   kubectl delete serviceaccount kindnet -n kube-system --ignore-not-found
+        #   kubectl delete daemonset kindnet -n kube-system --ignore-not-found
+        # }
 
         if ! kind get clusters | grep -q kind; then
-          clean_kindnet_resources
-          kind delete cluster
+          # clean_kindnet_resources
+          # kind delete cluster
           echo "Creating directory for etcd storage"
           sudo mkdir -p /mnt/storage/etcd
           echo "Creating Kind cluster using kind-1es.yaml"
           if ! kind create cluster --config .github/workflows/kind-cluster/kind-1es.yaml; then
             echo "Failed to create cluster on first attempt. Cleaning and retrying..."
-            clean_kindnet_resources
-            kind delete cluster
+            # clean_kindnet_resources
+            # kind delete cluster
             sleep 15
             if ! kind create cluster --config .github/workflows/kind-cluster/kind-1es.yaml; then
               echo "Failed to create cluster on second attempt. Exiting."
