fix: cluster

diff --git a/.github/actions/build-image-action/action.yml b/.github/actions/build-image-action/action.yml
--- a/.github/actions/build-image-action/action.yml
+++ b/.github/actions/build-image-action/action.yml
@@ -88,80 +88,42 @@ runs:
 
     - name: Check and Create Kind Cluster
       run: |
-        if ! kind get clusters | grep -q kind; then
-          # Check if kubectl can communicate with the cluster
-          if kubectl cluster-info &> /dev/null; then
-            kubectl cluster-info --context kind-kind
-            # Delete leftover kindnet resources if they exist
-            kubectl delete clusterrole kindnet --ignore-not-found || true
-            kubectl delete clusterrolebinding kindnet --ignore-not-found || true
-            kubectl delete serviceaccount kindnet -n kube-system --ignore-not-found || true
-            kubectl delete daemonset kindnet -n kube-system --ignore-not-found || true
-            kind delete cluster
+        export KUBECONFIG=~/.kube/config
+        echo "Using kubeconfig at $KUBECONFIG."
+
+        function clean_kindnet_resources() {
+          if ! kubectl cluster-info &> /dev/null; then
+            echo "Cannot reach cluster. Skipping cleanup."
+            return
           fi
 
+          echo "Cleaning up kindnet resources..."
+          kubectl delete clusterrole kindnet --ignore-not-found
+          kubectl delete clusterrolebinding kindnet --ignore-not-found
+          kubectl delete serviceaccount kindnet -n kube-system --ignore-not-found
+          kubectl delete daemonset kindnet -n kube-system --ignore-not-found
+        }
+
+        if ! kind get clusters | grep -q kind; then
+          clean_kindnet_resources
+          kind delete cluster
           echo "Creating directory for etcd storage"
           sudo mkdir -p /mnt/storage/etcd
-
-          create_kind_cluster() {
-            echo "Creating Kind cluster using kind-1es.yaml"
-            kind create cluster --config .github/workflows/kind-cluster/kind-1es.yaml
-            kubectl cluster-info --context kind-kind
-          }
-         if ! create_kind_cluster; then
-            echo "Kind cluster creation failed. Attempting to delete and retry..."
-
-            # Retrieve the kubeconfig content for the kind cluster
-            KUBECONFIG_CONTENT=$(kind get kubeconfig --name="kind")
-
-            if [ -z "$KUBECONFIG_CONTENT" ]; then
-              echo "Failed to retrieve the kubeconfig content."
-              exit 1
-            fi
-
-            # Write the kubeconfig content to a temporary file
-            echo "$KUBECONFIG_CONTENT" > /tmp/kubeconfig
-
-            # Set the correct permissions for the kubeconfig file
-            chmod 600 /tmp/kubeconfig
-
-            # Extract the server URL from the kubeconfig content using yq
-            KUBERNETES_CONTROL_PLANE_URL=$(echo "$KUBECONFIG_CONTENT" | yq eval '.clusters[0].cluster.server' -)
-
-            if [ -z "$KUBERNETES_CONTROL_PLANE_URL" ]; then
-              echo "Failed to retrieve the control plane URL."
-              exit 1
-            fi
-
-            echo "Kubernetes control plane URL: $KUBERNETES_CONTROL_PLANE_URL"
-
-            # Update the kubeconfig file with the correct URL
-            sed -i "s|server: .*|server: $KUBERNETES_CONTROL_PLANE_URL|" /tmp/kubeconfig
-
-            # Set the KUBECONFIG environment variable to the temporary kubeconfig file
-            export KUBECONFIG=/tmp/kubeconfig
-
-            # Set the context to use the updated cluster
-            kubectl config use-context kind-kind || true
-
-            # Verify the Kubernetes configuration 
-            kubectl cluster-info || true
-
-            # Delete leftover kindnet resources if they exist
-            kubectl delete clusterrole kindnet --ignore-not-found || true
-            kubectl delete clusterrolebinding kindnet --ignore-not-found || true
-            kubectl delete serviceaccount kindnet -n kube-system --ignore-not-found || true
-            kubectl delete daemonset kindnet -n kube-system --ignore-not-found || true
+          echo "Creating Kind cluster using kind-1es.yaml"
+          if ! kind create cluster --config .github/workflows/kind-cluster/kind-1es.yaml; then
+            echo "Failed to create cluster on first attempt. Cleaning and retrying..."
+            clean_kindnet_resources
             kind delete cluster
-            
-            # Ensure deletion
             sleep 15
-
-            if ! create_kind_cluster; then
-              echo "Kind cluster creation failed again. Exiting."
+            if ! kind create cluster --config .github/workflows/kind-cluster/kind-1es.yaml; then
+              echo "Failed to create cluster on second attempt. Exiting."
               exit 1
             fi
-         fi
+          fi
+        else
+          echo "Kind cluster already exists."
+          kubectl cluster-info
+        fi
       shell: bash
 
     - name: Check if Image exists in target ACR
