skip step need be

diff --git a/.github/workflows/preset-image-build.yml b/.github/workflows/preset-image-build.yml
--- a/.github/workflows/preset-image-build.yml
+++ b/.github/workflows/preset-image-build.yml
@@ -262,7 +262,12 @@ jobs:
 
       - name: Install Azure CLI latest
         run: |
-          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+          if ! which az > /dev/null; then
+            echo "Azure CLI not found. Installing..."
+            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+          else
+            echo "Azure CLI already installed."
+          fi
       
       - name: 'Az CLI login'
         uses: azure/login@v1.4.6
