Apply security best practices
Signed-off-by: Heba Elayoty <hebaelayoty@gmail.com>

diff --git a/.github/workflows/preset-image-build.yml b/.github/workflows/preset-image-build.yml
--- a/.github/workflows/preset-image-build.yml
+++ b/.github/workflows/preset-image-build.yml
@@ -25,30 +25,35 @@ on:
         description: "Run all models for build"
 
 env:
-    GO_VERSION: "1.20"
-    BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
+  GO_VERSION: "1.20"
+  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 
 permissions:
   id-token: write
   contents: read
 
 jobs:
-  determine-models: 
+  determine-models:
     runs-on: ubuntu-latest
     environment: preset-env
     outputs:
       matrix: ${{ steps.affected_models.outputs.matrix }}
       is_matrix_empty: ${{ steps.check_matrix_empty.outputs.is_empty }}
-    steps: 
+    steps:
+      - name: Harden Runner
+        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
+        with:
+          egress-policy: audit
+
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
         with:
           submodules: true
           fetch-depth: 0
-      
+
       - name: Set FORCE_RUN_ALL Flag
         run: echo "FORCE_RUN_ALL=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.force-run-all == 'true' }}" >> $GITHUB_ENV
-      
+
       # This script should output a JSON array of model names
       - name: Determine Affected Models
         id: affected_models
@@ -56,11 +61,11 @@ jobs:
           PR_BRANCH=${{ env.BRANCH_NAME }} \
           FORCE_RUN_ALL=${{ env.FORCE_RUN_ALL }} \
           python3 .github/workflows/kind-cluster/determine_models.py
-            
+
       - name: Print Determined Models
         run: |
           echo "Output from affected_models: ${{ steps.affected_models.outputs.matrix }}"
-      
+
       - name: Check if Matrix is Empty
         id: check_matrix_empty
         run: |
@@ -69,7 +74,7 @@ jobs:
           else
             echo "is_empty=false" >> $GITHUB_OUTPUT
           fi
-  
+
   build-models:
     needs: determine-models
     if: needs.determine-models.outputs.is_matrix_empty == 'false'
@@ -81,31 +86,36 @@ jobs:
         model: ${{fromJson(needs.determine-models.outputs.matrix)}}
       max-parallel: 3
     steps:
+      - name: Harden Runner
+        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
+        with:
+          egress-policy: audit
+
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
         with:
           submodules: true
           fetch-depth: 0
-      
+
       - name: Check Available Disk Space
         run: df -h
 
       - name: Install Azure CLI latest
         run: |
-              if ! which az > /dev/null; then
-                  echo "Azure CLI not found. Installing..."
-                  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
-              else
-                  echo "Azure CLI already installed."
-              fi
-    
+          if ! which az > /dev/null; then
+              echo "Azure CLI not found. Installing..."
+              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+          else
+              echo "Azure CLI already installed."
+          fi
+
       - name: 'Az CLI login'
-        uses: azure/login@v1.6.1
+        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
         with:
-            client-id: ${{ secrets.AZURE_CLIENT_ID }}
-            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-            allow-no-subscriptions: true
-        
+          client-id: ${{ secrets.AZURE_CLIENT_ID }}
+          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+          allow-no-subscriptions: true
+
       - name: 'Set subscription'
         run: az account set --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}
 
@@ -118,29 +128,29 @@ jobs:
           echo "ACR_NAME=$ACR_NAME" >> $GITHUB_OUTPUT
           echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_OUTPUT
           echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_OUTPUT
-      
+
       - name: 'Check if Image exists in Test ACR'
         id: check_test_image
         run: |
-            ACR_NAME=${{ steps.acr_info.outputs.ACR_USERNAME }}
-            IMAGE_NAME=${{ matrix.model.name }}
-            TAG=${{ matrix.model.tag }}
+          ACR_NAME=${{ steps.acr_info.outputs.ACR_USERNAME }}
+          IMAGE_NAME=${{ matrix.model.name }}
+          TAG=${{ matrix.model.tag }}
+          
+          # Use '|| true' to prevent script from exiting with an error if the repository is not found
+          TAGS=$(az acr repository show-tags -n $ACR_NAME --repository $IMAGE_NAME --output tsv || true)
+          
+          if [[ -z "$TAGS" ]]; then
+              echo "Image $IMAGE_NAME:$TAG or repository not found in $ACR_NAME."
+              echo "IMAGE_EXISTS=false" >> $GITHUB_OUTPUT
+          else
+              if echo "$TAGS" | grep -q "^$TAG$"; then
+                  echo "IMAGE_EXISTS=true" >> $GITHUB_OUTPUT
+              else
+                  echo "IMAGE_EXISTS=false" >> $GITHUB_OUTPUT
+                  echo "Image $IMAGE_NAME:$TAG not found in $ACR_NAME."
+              fi
+          fi
 
-            # Use '|| true' to prevent script from exiting with an error if the repository is not found
-            TAGS=$(az acr repository show-tags -n $ACR_NAME --repository $IMAGE_NAME --output tsv || true)
-
-            if [[ -z "$TAGS" ]]; then
-                echo "Image $IMAGE_NAME:$TAG or repository not found in $ACR_NAME."
-                echo "IMAGE_EXISTS=false" >> $GITHUB_OUTPUT
-            else
-                if echo "$TAGS" | grep -q "^$TAG$"; then
-                    echo "IMAGE_EXISTS=true" >> $GITHUB_OUTPUT
-                else
-                    echo "IMAGE_EXISTS=false" >> $GITHUB_OUTPUT
-                    echo "Image $IMAGE_NAME:$TAG not found in $ACR_NAME."
-                fi
-            fi
-      
       - name: Launch Python Script to Kickoff Build Jobs
         if: steps.check_test_image.outputs.IMAGE_EXISTS == 'false'
         id: launch_script
