fix: mountpoint

diff --git a/.github/workflows/preset-image-build.yml b/.github/workflows/preset-image-build.yml
--- a/.github/workflows/preset-image-build.yml
+++ b/.github/workflows/preset-image-build.yml
@@ -40,16 +40,9 @@ jobs:
       - name: List All Disks
         run: |
           lsblk
-          if ! lsblk /dev/sda1 &> /dev/null; then
-            echo "Failed to find required disk /dev/sda1"
+          if ! mountpoint -q /mnt/storage; then
+            echo "Failed to find required storage partition /mnt/storage"
             exit 1
-          fi
-
-      - name: Mount /dev/sda1
-        run: |
-          if ! mountpoint -q /datadrive; then
-            sudo mkdir -p /datadrive
-            sudo mount /dev/sda1 /datadrive
           fi
 
       - name: Check Available Disk Space
